name: kan-memristor
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - ipykernel
  - tqdm
  - sympy
  - h5py
  - pyyaml
  - pytest
  - pytorch
  - torchaudio
  - cpuonly
  - pip:
      - pykan
