"""Hardware-oriented odd-polynomial KAN edge simulation."""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from kan_memristor.hardware.gilbert_multiplier import GilbertMultiplier, GilbertMultiplierParameters
from kan_memristor.hardware.memristor import RRAMWeightMapper


@dataclass(frozen=True)
class HardwareOddPolynomialEdge:
    """Simulate phi(x) = c1*x + c3*x^3 + c5*x^5 using hardware blocks.

    Coefficients are mapped to differential RRAM conductance pairs. Powers are
    generated by repeated Gilbert multiplications. Inputs are expected to be
    normalized and then scaled into the multiplier's voltage range.
    """

    coefficients: tuple[float, float, float]
    input_scale_v: float = 0.4
    mapper: RRAMWeightMapper = RRAMWeightMapper()
    multiplier_parameters: GilbertMultiplierParameters = GilbertMultiplierParameters()

    def mapped_coefficients(self) -> np.ndarray:
        coeffs = np.asarray(self.coefficients, dtype=float)
        g_pos, g_neg, max_abs = self.mapper.signed_weight_to_differential_pair(coeffs)
        return self.mapper.differential_pair_to_weight(g_pos, g_neg, max_abs)

    def powers(self, x_normalized: np.ndarray | float) -> np.ndarray:
        multiplier = GilbertMultiplier(self.multiplier_parameters)
        x_v = np.asarray(x_normalized, dtype=float) * self.input_scale_v
        x1 = x_v
        x3 = multiplier.cascade_power(x_v, 3)
        x5 = multiplier.cascade_power(x_v, 5)
        return np.stack([x1, x3, x5], axis=-1)

    def __call__(self, x_normalized: np.ndarray | float) -> np.ndarray:
        return np.einsum("...k,k->...", self.powers(x_normalized), self.mapped_coefficients())