"""Memristive odd-polynomial KAN layers and pulse-based training.

This module supports two hardware simulation levels.

* Finite-state mode: conductance updates jump between ideal RRAM levels.
* Complete physical mode: x^3 and x^5 rows are generated by a differentiable
  Gilbert multiplier approximation, and SET/RESET updates evolve memdiode state
  with the DynamicMemdiode compact model before conductance is read back.

The second mode is still a compact simulation rather than SPICE, but it routes
learning through the device equations instead of directly editing weights.
"""

from __future__ import annotations

from dataclasses import dataclass, replace
from typing import Iterable

import numpy as np
import torch
from torch import nn

from kan_memristor.hardware.gilbert_multiplier import GilbertMultiplierParameters
from kan_memristor.hardware.memristor import DynamicMemdiode, DynamicMemdiodeParameters, RRAMWeightMapper
from kan_memristor.models import OddPolynomialKAN, OddPolynomialKANLayer, apply_inter_layer_normalization


@dataclass(frozen=True)
class HardwareKANScaling:
    """Fixed circuit scaling for a physical KAN layer."""

    input_scale_v: float = 0.2
    current_to_voltage_gain: float | None = None
    conductance_utilization: float = 0.85

    def __post_init__(self) -> None:
        if self.input_scale_v <= 0.0:
            raise ValueError("input_scale_v must be positive")
        if self.current_to_voltage_gain is not None and self.current_to_voltage_gain <= 0.0:
            raise ValueError("current_to_voltage_gain must be positive")
        if not 0.0 < self.conductance_utilization <= 1.0:
            raise ValueError("conductance_utilization must be in (0, 1]")


@dataclass(frozen=True)
class PhysicalForwardConfig:
    """Nonideal forward-path options for the physical KAN."""

    use_gilbert_multiplier: bool = False
    gilbert_parameters: GilbertMultiplierParameters = GilbertMultiplierParameters()
    rram_iv_nonlinearity: float = 0.0
    adc_clip_voltage: float | None = None
    inter_layer_normalization: str = "none"
    normalization_gain: float = 1.0

    def __post_init__(self) -> None:
        if self.rram_iv_nonlinearity < 0.0:
            raise ValueError("rram_iv_nonlinearity must be non-negative")
        if self.adc_clip_voltage is not None and self.adc_clip_voltage <= 0.0:
            raise ValueError("adc_clip_voltage must be positive")
        apply_inter_layer_normalization(
            torch.zeros(1),
            mode=self.inter_layer_normalization,
            gain=self.normalization_gain,
        )


@dataclass(frozen=True)
class DynamicPulseConfig:
    """Voltage-pulse settings for DynamicMemdiode programming."""

    enabled: bool = False
    set_voltage: float = 1.8
    reset_voltage: float = -1.0
    pulse_width_s: float = 1e-9
    read_voltage: float = 0.2
    memdiode_parameters: DynamicMemdiodeParameters = DynamicMemdiodeParameters()

    def __post_init__(self) -> None:
        if self.set_voltage <= 0.0:
            raise ValueError("set_voltage must be positive")
        if self.reset_voltage >= 0.0:
            raise ValueError("reset_voltage must be negative")
        if self.pulse_width_s <= 0.0:
            raise ValueError("pulse_width_s must be positive")
        if self.read_voltage <= 0.0:
            raise ValueError("read_voltage must be positive")


class PhysicalOddPolynomialKANLayer(nn.Module):
    """Odd-polynomial KAN layer represented by differential RRAM pairs."""

    def __init__(
        self,
        in_features: int,
        out_features: int,
        powers: tuple[int, ...] = (1, 3, 5),
        mapper: RRAMWeightMapper | None = None,
        scaling: HardwareKANScaling | None = None,
        forward_config: PhysicalForwardConfig | None = None,
        dynamic_pulse_config: DynamicPulseConfig | None = None,
        bias: torch.Tensor | None = None,
    ) -> None:
        super().__init__()
        if not powers:
            raise ValueError("powers must not be empty")
        if any(power <= 0 or power % 2 == 0 for power in powers):
            raise ValueError("powers must be positive odd integers")
        self.in_features = in_features
        self.out_features = out_features
        self.mapper = mapper or RRAMWeightMapper()
        self.scaling = scaling or HardwareKANScaling()
        self.forward_config = forward_config or PhysicalForwardConfig()
        self.dynamic_pulse_config = dynamic_pulse_config or DynamicPulseConfig()
        self.register_buffer("powers", torch.tensor(powers, dtype=torch.float32))
        self.g_pos = nn.Parameter(torch.full((out_features, in_features, len(powers)), self.mapper.g_min))
        self.g_neg = nn.Parameter(torch.full((out_features, in_features, len(powers)), self.mapper.g_min))
        self.register_buffer("state_pos", torch.zeros(out_features, in_features, len(powers)))
        self.register_buffer("state_neg", torch.zeros(out_features, in_features, len(powers)))
        if bias is None:
            bias = torch.zeros(out_features, dtype=torch.float32)
        self.bias = nn.Parameter(bias.detach().clone().float())
        gain = self.scaling.current_to_voltage_gain or 1.0
        self.register_buffer("current_to_voltage_gain", torch.tensor(float(gain), dtype=torch.float32))

    @property
    def conductance_span(self) -> float:
        return self.mapper.g_max - self.mapper.g_min

    @classmethod
    def from_software_layer(
        cls,
        layer: OddPolynomialKANLayer,
        mapper: RRAMWeightMapper | None = None,
        scaling: HardwareKANScaling | None = None,
        forward_config: PhysicalForwardConfig | None = None,
        dynamic_pulse_config: DynamicPulseConfig | None = None,
    ) -> "PhysicalOddPolynomialKANLayer":
        """Map a trained software odd-polynomial layer onto RRAM pairs."""

        mapper = mapper or RRAMWeightMapper()
        scaling = scaling or HardwareKANScaling()
        coefficients = layer.coefficients.detach().cpu().float()
        max_abs = float(coefficients.abs().max().item()) if coefficients.numel() else 1.0
        span = mapper.g_max - mapper.g_min
        gain = scaling.current_to_voltage_gain
        if gain is None:
            gain = max(max_abs / (scaling.conductance_utilization * span * scaling.input_scale_v), 1.0)
            scaling = replace(scaling, current_to_voltage_gain=gain)
        physical = cls(
            layer.in_features,
            layer.out_features,
            powers=tuple(int(power.item()) for power in layer.powers),
            mapper=mapper,
            scaling=scaling,
            forward_config=forward_config,
            dynamic_pulse_config=dynamic_pulse_config,
            bias=layer.bias.detach().cpu(),
        )
        physical.current_to_voltage_gain.fill_(float(gain))
        desired_delta_g = coefficients / (float(gain) * scaling.input_scale_v)
        desired_delta_g = desired_delta_g.clamp(min=-span, max=span)
        g_pos = torch.full_like(desired_delta_g, mapper.g_min) + desired_delta_g.clamp_min(0.0)
        g_neg = torch.full_like(desired_delta_g, mapper.g_min) + (-desired_delta_g).clamp_min(0.0)
        with torch.no_grad():
            physical.g_pos.copy_(physical.quantize(g_pos))
            physical.g_neg.copy_(physical.quantize(g_neg))
            physical.sync_states_from_conductance_()
        return physical

    def quantize(self, conductance: torch.Tensor) -> torch.Tensor:
        levels = torch.linspace(
            self.mapper.g_min,
            self.mapper.g_max,
            self.mapper.n_states,
            dtype=conductance.dtype,
            device=conductance.device,
        )
        indices = torch.abs(conductance.unsqueeze(-1) - levels).argmin(dim=-1)
        return levels[indices]

    def state_to_conductance(self, state: torch.Tensor) -> torch.Tensor:
        return self.mapper.g_min + state.clamp(0.0, 1.0) * self.conductance_span

    def conductance_to_state(self, conductance: torch.Tensor) -> torch.Tensor:
        return ((conductance - self.mapper.g_min) / self.conductance_span).clamp(0.0, 1.0)

    def sync_states_from_conductance_(self) -> None:
        self.state_pos.copy_(self.conductance_to_state(self.g_pos.detach()))
        self.state_neg.copy_(self.conductance_to_state(self.g_neg.detach()))

    def sync_conductance_from_states_(self, quantize: bool = True) -> None:
        g_pos = self.state_to_conductance(self.state_pos)
        g_neg = self.state_to_conductance(self.state_neg)
        if quantize:
            g_pos = self.quantize(g_pos)
            g_neg = self.quantize(g_neg)
        self.g_pos.copy_(g_pos.clamp(self.mapper.g_min, self.mapper.g_max))
        self.g_neg.copy_(g_neg.clamp(self.mapper.g_min, self.mapper.g_max))

    def effective_coefficients(self) -> torch.Tensor:
        """Return dimensionless coefficients implied by the physical layer."""

        return self.current_to_voltage_gain * self.scaling.input_scale_v * (self.g_pos - self.g_neg)

    def _gilbert_multiply_torch(self, x: torch.Tensor, y: torch.Tensor) -> torch.Tensor:
        p = self.forward_config.gilbert_parameters
        x_eff = x
        y_eff = y
        if p.soft_clip:
            x_eff = p.input_linear_range * torch.tanh(x / p.input_linear_range)
            y_eff = p.input_linear_range * torch.tanh(y / p.input_linear_range)
        else:
            x_eff = x.clamp(-p.input_linear_range, p.input_linear_range)
            y_eff = y.clamp(-p.input_linear_range, p.input_linear_range)
        output = p.product_gain * x_eff * y_eff
        return output.clamp(-0.5 * p.supply_voltage, 0.5 * p.supply_voltage)

    def voltage_rows(self, x: torch.Tensor) -> torch.Tensor:
        x_v = self.scaling.input_scale_v * x
        if not self.forward_config.use_gilbert_multiplier:
            return self.scaling.input_scale_v * x.unsqueeze(-1).pow(self.powers.to(x.device, x.dtype))

        rows: list[torch.Tensor] = []
        for power_tensor in self.powers:
            power = int(power_tensor.item())
            if power == 1:
                rows.append(x_v)
                continue
            result = x_v
            for _ in range(power - 1):
                result = self._gilbert_multiply_torch(result, x_v)
            rows.append(result)
        return torch.stack(rows, dim=-1)

    def branch_current(self, conductance: torch.Tensor, voltage_rows: torch.Tensor) -> torch.Tensor:
        if self.forward_config.rram_iv_nonlinearity <= 0.0:
            return torch.einsum("bik,oik->bo", voltage_rows, conductance)
        read_v = max(self.mapper.read_voltage, 1e-12)
        scale = 1.0 + self.forward_config.rram_iv_nonlinearity * (voltage_rows / read_v).pow(2)
        return torch.einsum("bik,oik->bo", voltage_rows * scale, conductance)

    def edge_currents(self, x: torch.Tensor) -> torch.Tensor:
        rows = self.voltage_rows(x)
        return self.branch_current(self.g_pos, rows) - self.branch_current(self.g_neg, rows)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        currents = self.edge_currents(x)
        output = self.current_to_voltage_gain.to(x.device, x.dtype) * currents + self.bias.to(x.device, x.dtype)
        clip = self.forward_config.adc_clip_voltage
        if clip is not None:
            output = output.clamp(-clip, clip)
        return output

    def clamp_and_quantize_(self) -> None:
        with torch.no_grad():
            self.g_pos.clamp_(self.mapper.g_min, self.mapper.g_max)
            self.g_neg.clamp_(self.mapper.g_min, self.mapper.g_max)
            self.g_pos.copy_(self.quantize(self.g_pos))
            self.g_neg.copy_(self.quantize(self.g_neg))
            self.sync_states_from_conductance_()

    def apply_dynamic_memdiode_pulses_(self, conductance: nn.Parameter, pulses: torch.Tensor, polarity: str) -> None:
        """Update a conductance tensor by voltage pulses through DynamicMemdiode."""

        if polarity not in {"set", "reset"}:
            raise ValueError("polarity must be 'set' or 'reset'")
        state = self.state_pos if conductance is self.g_pos else self.state_neg
        states_np = state.detach().cpu().numpy().astype(float)
        pulses_np = pulses.detach().cpu().numpy().astype(int)
        if pulses_np.max(initial=0) <= 0:
            return
        cfg = self.dynamic_pulse_config
        voltage = cfg.set_voltage if polarity == "set" else cfg.reset_voltage
        device = DynamicMemdiode(cfg.memdiode_parameters)
        for _ in range(int(pulses_np.max())):
            active = pulses_np > 0
            if not np.any(active):
                break
            derivative = device.state_derivative(voltage, state=states_np)
            states_np = np.where(active, np.clip(states_np + cfg.pulse_width_s * derivative, 0.0, 1.0), states_np)
            pulses_np = np.where(active, pulses_np - 1, pulses_np)
        state.copy_(torch.as_tensor(states_np, dtype=state.dtype, device=state.device))
        self.sync_conductance_from_states_()


class PhysicalOddPolynomialKAN(nn.Module):
    """Stack of memristive odd-polynomial KAN layers."""

    def __init__(self, layers: Iterable[PhysicalOddPolynomialKANLayer]) -> None:
        super().__init__()
        self.layers = nn.ModuleList(list(layers))
        if not self.layers:
            raise ValueError("PhysicalOddPolynomialKAN requires at least one layer")

    @classmethod
    def from_software_model(
        cls,
        model: OddPolynomialKAN,
        mapper: RRAMWeightMapper | None = None,
        input_scale_v: float = 0.2,
        current_to_voltage_gain: float | None = None,
        forward_config: PhysicalForwardConfig | None = None,
        dynamic_pulse_config: DynamicPulseConfig | None = None,
    ) -> "PhysicalOddPolynomialKAN":
        layers: list[PhysicalOddPolynomialKANLayer] = []
        for software_layer in model.layers:
            scaling = HardwareKANScaling(
                input_scale_v=input_scale_v,
                current_to_voltage_gain=current_to_voltage_gain,
            )
            layers.append(
                PhysicalOddPolynomialKANLayer.from_software_layer(
                    software_layer,
                    mapper=mapper,
                    scaling=scaling,
                    forward_config=forward_config,
                    dynamic_pulse_config=dynamic_pulse_config,
                )
            )
        return cls(layers)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        for index, layer in enumerate(self.layers):
            x = layer(x)
            if index < len(self.layers) - 1:
                x = apply_inter_layer_normalization(
                    x,
                    mode=layer.forward_config.inter_layer_normalization,
                    gain=layer.forward_config.normalization_gain,
                )
        return x

    def conductance_parameters(self) -> list[nn.Parameter]:
        params: list[nn.Parameter] = []
        for layer in self.layers:
            params.extend([layer.g_pos, layer.g_neg])
        return params

    def clamp_and_quantize_(self) -> None:
        for layer in self.layers:
            layer.clamp_and_quantize_()

    def count_memristors(self) -> int:
        return sum(layer.g_pos.numel() + layer.g_neg.numel() for layer in self.layers)

    def count_gilbert_multipliers(self) -> int:
        count = 0
        for layer in self.layers:
            count += layer.in_features * sum(max(int(power.item()) - 1, 0) for power in layer.powers)
        return count


@dataclass(frozen=True)
class PulseUpdateConfig:
    """SET/RESET pulse optimizer settings."""

    max_pulses_per_update: int = 1
    gradient_deadzone_quantile: float = 0.5
    bias_learning_rate: float = 1e-3
    conductance_learning_rate: float = 1e-10
    quantize_after_update: bool = True
    dynamic_pulse_config: DynamicPulseConfig = DynamicPulseConfig()

    def __post_init__(self) -> None:
        if self.max_pulses_per_update < 1:
            raise ValueError("max_pulses_per_update must be at least 1")
        if not 0.0 <= self.gradient_deadzone_quantile < 1.0:
            raise ValueError("gradient_deadzone_quantile must be in [0, 1)")
        if self.conductance_learning_rate <= 0.0:
            raise ValueError("conductance_learning_rate must be positive")


class MemristivePulseOptimizer:
    """Manual optimizer that converts gradients into SET/RESET pulse requests."""

    def __init__(self, model: PhysicalOddPolynomialKAN, config: PulseUpdateConfig | None = None) -> None:
        self.model = model
        self.config = config or PulseUpdateConfig()
        self.total_set_pulses = 0
        self.total_reset_pulses = 0
        self._residuals: dict[int, torch.Tensor] = {}

    def zero_grad(self) -> None:
        for parameter in self.model.parameters():
            parameter.grad = None

    def _pulse_tensors(self, conductance: nn.Parameter, grad: torch.Tensor, threshold: torch.Tensor, g_step: float) -> tuple[torch.Tensor, torch.Tensor]:
        abs_grad = grad.abs()
        desired = -self.config.conductance_learning_rate * grad
        desired = torch.where(abs_grad >= threshold, desired, torch.zeros_like(desired))
        residual = self._residuals.setdefault(id(conductance), torch.zeros_like(conductance))
        residual.add_(desired)
        pulses = torch.floor(residual.abs() / g_step).to(torch.int64)
        pulses = pulses.clamp(min=0, max=self.config.max_pulses_per_update)
        set_pulses = torch.where(residual > 0.0, pulses, torch.zeros_like(pulses))
        reset_pulses = torch.where(residual < 0.0, pulses, torch.zeros_like(pulses))
        residual.sub_((set_pulses.to(conductance.dtype) - reset_pulses.to(conductance.dtype)) * g_step)
        return set_pulses, reset_pulses

    def step(self) -> dict[str, int]:
        step_set = 0
        step_reset = 0
        with torch.no_grad():
            for layer in self.model.layers:
                g_step = (layer.mapper.g_max - layer.mapper.g_min) / (layer.mapper.n_states - 1)
                for conductance in (layer.g_pos, layer.g_neg):
                    if conductance.grad is None:
                        continue
                    grad = conductance.grad
                    abs_grad = grad.abs()
                    max_grad = float(abs_grad.max().item()) if abs_grad.numel() else 0.0
                    if max_grad <= 0.0:
                        continue
                    if self.config.gradient_deadzone_quantile > 0.0:
                        threshold = torch.quantile(abs_grad.flatten(), self.config.gradient_deadzone_quantile)
                    else:
                        threshold = torch.tensor(0.0, dtype=abs_grad.dtype, device=abs_grad.device)
                    set_pulses, reset_pulses = self._pulse_tensors(conductance, grad, threshold, g_step)
                    if self.config.dynamic_pulse_config.enabled:
                        layer.apply_dynamic_memdiode_pulses_(conductance, set_pulses, "set")
                        layer.apply_dynamic_memdiode_pulses_(conductance, reset_pulses, "reset")
                    else:
                        delta = (set_pulses.to(conductance.dtype) - reset_pulses.to(conductance.dtype)) * g_step
                        conductance.add_(delta)
                    step_set += int(set_pulses.sum().item())
                    step_reset += int(reset_pulses.sum().item())
                if layer.bias.grad is not None and self.config.bias_learning_rate > 0.0:
                    layer.bias.add_(-self.config.bias_learning_rate * layer.bias.grad)
                if self.config.dynamic_pulse_config.enabled:
                    layer.sync_conductance_from_states_(quantize=self.config.quantize_after_update)
                elif self.config.quantize_after_update:
                    layer.clamp_and_quantize_()
                else:
                    layer.g_pos.clamp_(layer.mapper.g_min, layer.mapper.g_max)
                    layer.g_neg.clamp_(layer.mapper.g_min, layer.mapper.g_max)
                    layer.sync_states_from_conductance_()
        self.total_set_pulses += step_set
        self.total_reset_pulses += step_reset
        self.zero_grad()
        return {"set_pulses": step_set, "reset_pulses": step_reset}


